### DISCUSSION TITLE
Action fails despite regex being correct?

### DISCUSSION THREAD

**Discussion by lostdesign** [GsActions/commit-message-checker#85] [Q&A]
Hi there, here is my example https://regexr.com/71ack and the config looks like:

```yml
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]) .+$'
          flags: 'gi'
          error: 'Your first line has to contain a commit type like "✨ add map".'
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

```

Does anyone know why it fails while the regex and message are valid? Here is the failing job https://github.com/bos-wiki/website/actions/runs/3361760088/jobs/5572579154
