### DISCUSSION TITLE
Conditional workflow

### DISCUSSION THREAD

**Discussion by klacol** [GsActions/commit-message-checker#87] [Q&A]
Hi, great action here. I cannot figure out, how to get the result of the check. I want to run a step, only, if the commit message check fails. 

Something like this:

```yml
jobs:
  check-commit-message:
    name: Commit Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        uses: gsactions/commit-message-checker@v2
        id: check-commit-message
        continue-on-error: true
        with:
          pattern: '(KP|IT|FO|FM)-\d+[^\S\r\n]'
          flags: 'gm'
          error: 'Die Commit-Message entspricht nicht den eTASK-Regeln. Bitte korrigiere sie.'
          excludeDescription: 'false' # optional: this does not exclude the description body of a pull request
          excludeTitle: 'false ' # optional: this does not exclude the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GH_TOKEN }} # github access token is only required if checkAllCommitMessages is true     
      - name: Set branch protection rule
        if: steps.check-commit-message.conclusion  == 'failure'
        run: "echo 'Set branch protection rule'"
      - name: Finalize
        if: steps.check-commit-message.conclusion  == 'success'
        run: "echo 'Die Commit Message ist ok! Danke.'"
```

But it seems, that the value of `steps.check-commit-message.conclusion` has always the value `success`.
