### ISSUE TITLE
[bug] somehow it detects commits that i have since force-pushed myself away from

### ISSUE THREAD

**Issue by C0DK** [GsActions/commit-message-checker#4]
in my repo i had a bad commit, so i renamed it and force pushed in my PR however the check still fails somehow, and shows the old message. It seems it catches something in the wrong way.

On top of this, if i let this run on my master branch, it will fail on my newest commit because i have a really old commit that doesn't conform the my naming convetion, rather than only checking the commit at hand. should i use another regex flag? (for thsi reason i disabled the check on anything but pull requests)

```yml
name: "Commit Message Check"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(ID-\d+|FIX): .+'
          flags: "gm"
          error: "Naming convention is `[ID]: [summary]` i.e `ID-404: Fixed My Shit`"

```
